import type { PanelProduct, Category, Review } from './types';
import { PANEL_SIZES, DESIGN_OVERLAY_PRICE } from '../../../shared/config/constants';

export const categories: Category[] = [
  { key: 'all', label: 'Все дизайны', image: '', count: 0 },
  { key: 'wood', label: 'Дерево', image: 'https://images.unsplash.com/photo-1644925757334-d0397c01518c?w=400&h=300&fit=crop', count: 3 },
  { key: 'stone', label: 'Камень', image: 'https://images.unsplash.com/photo-1566041510394-cf7c8fe21800?w=400&h=300&fit=crop', count: 2 },
  { key: 'abstract', label: 'Абстракция', image: 'https://images.unsplash.com/photo-1740686004244-e9bc7c75d8e5?w=400&h=300&fit=crop', count: 2 },
  { key: 'geometric', label: 'Геометрия', image: 'https://images.unsplash.com/photo-1582135739786-3bceafcaea85?w=400&h=300&fit=crop', count: 2 },
  { key: 'nature', label: 'Природа', image: 'https://images.unsplash.com/photo-1722109997425-40f920848aed?w=400&h=300&fit=crop', count: 2 },
  { key: 'minimal', label: 'Минимализм', image: 'https://images.unsplash.com/photo-1584530313715-bfe628686135?w=400&h=300&fit=crop', count: 2 },
];

export const products: PanelProduct[] = [
  {
    id: 'design-oak-classic',
    name: 'Дубовая классика',
    category: 'wood',
    categoryLabel: 'Дерево',
    style: 'Классика',
    material: 'Накладка с текстурой дуба',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: 'https://images.unsplash.com/photo-1644925757334-d0397c01518c?w=600&h=600&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1644925757334-d0397c01518c?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1611072337226-1140ab367200?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1763392199096-6efd9d28d8cc?w=800&h=600&fit=crop',
    ],
    description: 'Накладка с текстурой натурального дуба. Реалистичная фактура, тёплый древесный оттенок. Подходит для гостиных, кабинетов и спален.',
    specs: { 'Толщина накладки': '3 мм', 'Материал': 'Полимер с УФ-печатью', 'Класс': 'Премиум', 'Уход': 'Влажная уборка', 'Монтаж': 'Магнитное крепление' },
    colors: [
      { hex: '#8B6914', name: 'Натуральный дуб' },
      { hex: '#A0522D', name: 'Тёмный дуб' },
      { hex: '#D2B48C', name: 'Светлый дуб' },
      { hex: '#6B4226', name: 'Шоколад' },
    ],
    sizes: [...PANEL_SIZES],
    rating: 4.8,
    reviews: 124,
    badge: 'Хит',
    inStock: true,
    room: ['Гостиная', 'Кабинет', 'Спальня'],
    usageExamples: [
      { room: 'Гостиная', image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1200&h=800&fit=crop', caption: 'Тёплая текстура дуба создаёт атмосферу живого дерева. Каждая деталь в гармонии.' },
      { room: 'Кабинет', image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=800&fit=crop', caption: 'Концентрация и стиль. Рабочее пространство нового уровня.' },
      { room: 'Спальня', image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=1200&h=800&fit=crop', caption: 'Отдых в окружении тепла натурального дерева. Ночь — это ритуал.' },
    ],
  },
  {
    id: 'design-walnut',
    name: 'Американский орех',
    category: 'wood',
    categoryLabel: 'Дерево',
    style: 'Классика',
    material: 'Накладка с текстурой ореха',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: 'https://images.unsplash.com/photo-1611072337226-1140ab367200?w=600&h=600&fit=crop',
    gallery: [],
    description: 'Роскошная накладка с текстурой американского ореха. Глубокий шоколадный оттенок для элегантных интерьеров.',
    specs: { 'Толщина накладки': '3 мм', 'Материал': 'Полимер с УФ-печатью', 'Класс': 'Люкс', 'Уход': 'Влажная уборка', 'Монтаж': 'Магнитное крепление' },
    colors: [
      { hex: '#3E2723', name: 'Тёмный орех' },
      { hex: '#5D4037', name: 'Классический' },
      { hex: '#4E342E', name: 'Мокко' },
    ],
    sizes: [...PANEL_SIZES],
    rating: 4.9,
    reviews: 87,
    badge: 'Премиум',
    inStock: true,
    room: ['Гостиная', 'Кабинет'],
    usageExamples: [
      { room: 'Гостиная', image: 'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=1200&h=800&fit=crop', caption: 'Глубокий шоколадный тон — язык роскоши без лишних слов.' },
      { room: 'Кабинет', image: 'https://images.unsplash.com/photo-1486946255434-2466348c2166?w=1200&h=800&fit=crop', caption: 'Библиотека, где хочется думать. Тёмный орех задаёт ритм.' },
    ],
  },
  {
    id: 'design-ash',
    name: 'Ясень скандинавский',
    category: 'wood',
    categoryLabel: 'Дерево',
    style: 'Минимализм',
    material: 'Накладка с текстурой ясеня',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: 'https://images.unsplash.com/photo-1763392199096-6efd9d28d8cc?w=600&h=600&fit=crop',
    gallery: [],
    description: 'Светлая накладка в скандинавском стиле с текстурой ясеня. Минималистичный и воздушный дизайн.',
    specs: { 'Толщина накладки': '3 мм', 'Материал': 'Полимер с УФ-печатью', 'Класс': 'Премиум', 'Уход': 'Влажная уборка', 'Монтаж': 'Магнитное крепление' },
    colors: [
      { hex: '#F5DEB3', name: 'Натуральный' },
      { hex: '#FAEBD7', name: 'Отбелённый' },
      { hex: '#DEB887', name: 'Медовый' },
    ],
    sizes: [...PANEL_SIZES],
    rating: 4.7,
    reviews: 56,
    inStock: true,
    room: ['Спальня', 'Детская', 'Гостиная'],
    usageExamples: [
      { room: 'Спальня', image: 'https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=1200&h=800&fit=crop', caption: 'Скандинавская простота. Светлый ясень дарит воздух и свет.' },
      { room: 'Детская', image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&h=800&fit=crop', caption: 'Безопасный, лёгкий, радостный. Пространство для роста.' },
      { room: 'Гостиная', image: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=1200&h=800&fit=crop', caption: 'Минимализм, который согревает. Нордический дух в каждой линии.' },
    ],
  },
  {
    id: 'design-marble',
    name: 'Белый мрамор',
    category: 'stone',
    categoryLabel: 'Камень',
    style: 'Модерн',
    material: 'Накладка с текстурой мрамора',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: 'https://images.unsplash.com/photo-1566041510394-cf7c8fe21800?w=600&h=600&fit=crop',
    gallery: [],
    description: 'Изысканная мраморная текстура с тонкими прожилками. Элегантное решение для любого интерьера.',
    specs: { 'Толщина накладки': '3 мм', 'Материал': 'Полимер с УФ-печатью', 'Класс': 'Люкс', 'Уход': 'Влажная уборка', 'Монтаж': 'Магнитное крепление' },
    colors: [
      { hex: '#F5F5F5', name: 'Каррара' },
      { hex: '#E8E0D8', name: 'Калакатта' },
      { hex: '#D3D3D3', name: 'Серый мрамор' },
    ],
    sizes: [...PANEL_SIZES],
    rating: 4.8,
    reviews: 156,
    badge: 'Новинка',
    inStock: true,
    room: ['Гостиная', 'Ванная', 'Кухня'],
    usageExamples: [
      { room: 'Гостиная', image: 'https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=1200&h=800&fit=crop', caption: 'Мрамор — это вечный разговор о красоте. Бесконечно элегантно.' },
      { room: 'Ванная', image: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=1200&h=800&fit=crop', caption: 'Спа-атмосфера каждое утро. Белый мрамор как ритуал очищения.' },
      { room: 'Кухня', image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&h=800&fit=crop', caption: 'Кухня, достойная шеф-повара. Мрамор задаёт стандарт.' },
    ],
  },
  {
    id: 'design-concrete',
    name: 'Бетон лофт',
    category: 'stone',
    categoryLabel: 'Камень',
    style: 'Лофт',
    material: 'Накладка с текстурой бетона',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: 'https://images.unsplash.com/photo-1711606329941-63c1af645a53?w=600&h=600&fit=crop',
    gallery: [],
    description: 'Имитация бетонной поверхности для стиля лофт. Современный индустриальный вид.',
    specs: { 'Толщина накладки': '3 мм', 'Материал': 'Полимер с УФ-печатью', 'Класс': 'Стандарт', 'Уход': 'Влажная уборка', 'Монтаж': 'Магнитное крепление' },
    colors: [
      { hex: '#9E9E9E', name: 'Светлый бетон' },
      { hex: '#616161', name: 'Тёмный бетон' },
      { hex: '#BDBDBD', name: 'Серый' },
    ],
    sizes: [...PANEL_SIZES],
    rating: 4.5,
    reviews: 203,
    inStock: true,
    room: ['Гостиная', 'Кабинет', 'Кухня'],
    usageExamples: [
      { room: 'Гостиная', image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1200&h=800&fit=crop', caption: 'Индустриальный лофт. Бетон здесь не холодный — он честный.' },
      { room: 'Кухня', image: 'https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=1200&h=800&fit=crop', caption: 'Функция и характер. Кухня, где интересно готовить.' },
      { room: 'Кабинет', image: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1200&h=800&fit=crop', caption: 'Урбанистика как эстетика. Офис с позицией.' },
    ],
  },
  {
    id: 'design-waves',
    name: 'Волны',
    category: 'abstract',
    categoryLabel: 'Абстракция',
    style: 'Модерн',
    material: 'Накладка с абстрактным паттерном',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: 'https://images.unsplash.com/photo-1740686004244-e9bc7c75d8e5?w=600&h=600&fit=crop',
    gallery: [],
    description: 'Динамичный абстрактный паттерн с волнообразным рисунком. Создаёт движение и глубину.',
    specs: { 'Толщина накладки': '3 мм', 'Материал': 'Полимер с УФ-печатью', 'Класс': 'Премиум', 'Уход': 'Влажная уборка', 'Монтаж': 'Магнитное крепление' },
    colors: [
      { hex: '#1A237E', name: 'Индиго' },
      { hex: '#006064', name: 'Океан' },
      { hex: '#4A148C', name: 'Аметист' },
    ],
    sizes: [...PANEL_SIZES],
    rating: 4.7,
    reviews: 98,
    inStock: true,
    room: ['Гостиная', 'Спальня'],
    usageExamples: [
      { room: 'Гостиная', image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&h=800&fit=crop', caption: 'Движение как стиль. Волны задают ритм всему пространству.' },
      { room: 'Спальня', image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=800&fit=crop', caption: 'Глубина и спокойствие. Как будто смотришь в открытый океан.' },
    ],
  },
  {
    id: 'design-gradient',
    name: 'Градиент',
    category: 'abstract',
    categoryLabel: 'Абстракция',
    style: 'Арт',
    material: 'Накладка с градиентом',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: 'https://images.unsplash.com/photo-1690382285917-73dfd2a22d07?w=600&h=600&fit=crop',
    gallery: [],
    description: 'Плавные цветовые переходы. Арт-объект на вашей стене. Каждая панель уникальна.',
    specs: { 'Толщина накладки': '3 мм', 'Материал': 'Полимер с УФ-печатью', 'Класс': 'Премиум', 'Уход': 'Влажная уборка', 'Монтаж': 'Магнитное крепление' },
    colors: [
      { hex: '#FF6B6B', name: 'Закат' },
      { hex: '#4ECDC4', name: 'Мята' },
      { hex: '#2C3E50', name: 'Ночь' },
    ],
    sizes: [...PANEL_SIZES],
    rating: 4.6,
    reviews: 78,
    inStock: true,
    room: ['Гостиная', 'Кафе', 'Офис'],
    usageExamples: [
      { room: 'Гостиная', image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=1200&h=800&fit=crop', caption: 'Переход цвета меняет настроение комнаты от рассвета до заката.' },
      { room: 'Кафе', image: 'https://images.unsplash.com/photo-1445116572660-236099ec97a0?w=1200&h=800&fit=crop', caption: 'Арт-объект, который держит гостей дольше. Каждая панель — разговор.' },
      { room: 'Офис', image: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1200&h=800&fit=crop', caption: 'Цвет как инструмент. Градиент заряжает команду энергией.' },
    ],
  },
  {
    id: 'design-hexagon',
    name: 'Гексагон',
    category: 'geometric',
    categoryLabel: 'Геометрия',
    style: 'Модерн',
    material: 'Накладка с геометрическим паттерном',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: 'https://images.unsplash.com/photo-1582135739786-3bceafcaea85?w=600&h=600&fit=crop',
    gallery: [],
    description: 'Шестиугольный геометрический паттерн. Современный и стильный дизайн для любого пространства.',
    specs: { 'Толщина накладки': '3 мм', 'Материал': 'Полимер с УФ-печатью', 'Класс': 'Премиум', 'Уход': 'Влажная уборка', 'Монтаж': 'Магнитное крепление' },
    colors: [
      { hex: '#2D2D2D', name: 'Графит' },
      { hex: '#FFFFFF', name: 'Белый' },
      { hex: '#B87333', name: 'Медь' },
      { hex: '#1ABC9C', name: 'Бирюза' },
    ],
    sizes: [...PANEL_SIZES],
    rating: 4.5,
    reviews: 143,
    inStock: true,
    room: ['Ванная', 'Кухня', 'Прихожая'],
    usageExamples: [
      { room: 'Ванная', image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=1200&h=800&fit=crop', caption: 'Геометрия делает каждую плоскость высказыванием о форме.' },
      { room: 'Кухня', image: 'https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=1200&h=800&fit=crop', caption: 'Фартук из гексагонов. Кухня, которую хочется показывать.' },
      { room: 'Прихожая', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=800&fit=crop', caption: 'Первое впечатление — самое важное. Гексагон его создаёт.' },
    ],
  },
  {
    id: 'design-lines',
    name: 'Линии',
    category: 'geometric',
    categoryLabel: 'Геометрия',
    style: 'Минимализм',
    material: 'Накладка с линейным паттерном',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: 'https://images.unsplash.com/photo-1711606404173-0a45c4735639?w=600&h=600&fit=crop',
    gallery: [],
    description: 'Строгие вертикальные линии. Ритмичный минималистичный рисунок для элегантных интерьеров.',
    specs: { 'Толщина накладки': '3 мм', 'Материал': 'Полимер с УФ-печатью', 'Класс': 'Стандарт', 'Уход': 'Влажная уборка', 'Монтаж': 'Магнитное крепление' },
    colors: [
      { hex: '#FFFFFF', name: 'Белый' },
      { hex: '#1A1A1A', name: 'Чёрный' },
      { hex: '#9CA3AF', name: 'Серебро' },
    ],
    sizes: [...PANEL_SIZES],
    rating: 4.4,
    reviews: 89,
    inStock: true,
    room: ['Кабинет', 'Прихожая', 'Офис'],
    usageExamples: [
      { room: 'Кабинет', image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=800&fit=crop', caption: 'Ритм линий дисциплинирует мысль. Идеально для концентрации.' },
      { room: 'Прихожая', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=800&fit=crop', caption: 'Вертикаль уводит взгляд вверх. Пространство кажется выше.' },
      { room: 'Офис', image: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1200&h=800&fit=crop', caption: 'Строгость как стиль. Офис, где принимают серьёзные решения.' },
    ],
  },
  {
    id: 'design-tropical',
    name: 'Тропики',
    category: 'nature',
    categoryLabel: 'Природа',
    style: 'Модерн',
    material: 'Накладка с тропическим принтом',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: 'https://images.unsplash.com/photo-1722109997425-40f920848aed?w=600&h=600&fit=crop',
    gallery: [],
    description: 'Тропические листья и растения. Оживите интерьер природными мотивами.',
    specs: { 'Толщина накладки': '3 мм', 'Материал': 'Полимер с УФ-печатью', 'Класс': 'Премиум', 'Уход': 'Влажная уборка', 'Монтаж': 'Магнитное крепление' },
    colors: [
      { hex: '#2E7D32', name: 'Зелёный' },
      { hex: '#1B5E20', name: 'Тёмно-зелёный' },
      { hex: '#4CAF50', name: 'Свежая зелень' },
    ],
    sizes: [...PANEL_SIZES],
    rating: 4.6,
    reviews: 67,
    badge: 'Новинка',
    inStock: true,
    room: ['Спальня', 'Гостиная', 'Детская'],
    usageExamples: [
      { room: 'Спальня', image: 'https://images.unsplash.com/photo-1466781659-3bc5ee1b0e51?w=1200&h=800&fit=crop', caption: 'Природа внутри. Тропики дарят сон среди листвы.' },
      { room: 'Гостиная', image: 'https://images.unsplash.com/photo-1585128792020-803d29415281?w=1200&h=800&fit=crop', caption: 'Зеленью дышит каждый угол. Живой интерьер без ухода.' },
      { room: 'Детская', image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&h=800&fit=crop', caption: 'Дети растут в окружении природы. Пространство для воображения.' },
    ],
  },
  {
    id: 'design-botanical',
    name: 'Ботаника',
    category: 'nature',
    categoryLabel: 'Природа',
    style: 'Арт',
    material: 'Накладка с ботаническим принтом',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: 'https://images.unsplash.com/photo-1682698992719-966a930ccc90?w=600&h=600&fit=crop',
    gallery: [],
    description: 'Нежные ботанические иллюстрации. Утончённый дизайн для уютных пространств.',
    specs: { 'Толщина накладки': '3 мм', 'Материал': 'Полимер с УФ-печатью', 'Класс': 'Премиум', 'Уход': 'Влажная уборка', 'Монтаж': 'Магнитное крепление' },
    colors: [
      { hex: '#F5F5DC', name: 'Крем' },
      { hex: '#FFF8E1', name: 'Ваниль' },
      { hex: '#E8F5E9', name: 'Мятный' },
    ],
    sizes: [...PANEL_SIZES],
    rating: 4.8,
    reviews: 42,
    inStock: true,
    room: ['Спальня', 'Гостиная', 'Кафе'],
    usageExamples: [
      { room: 'Спальня', image: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1200&h=800&fit=crop', caption: 'Нежность ботаники как утренний свет. Просыпаться приятно.' },
      { room: 'Гостиная', image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1200&h=800&fit=crop', caption: 'Иллюстрации оживляют стену. Как страница из любимой книги.' },
      { room: 'Кафе', image: 'https://images.unsplash.com/photo-1445116572660-236099ec97a0?w=1200&h=800&fit=crop', caption: 'Атмосфера, в которую хочется возвращаться снова и снова.' },
    ],
  },
  {
    id: 'design-pure-white',
    name: 'Чистый белый',
    category: 'minimal',
    categoryLabel: 'Минимализм',
    style: 'Минимализм',
    material: 'Белая однотонная накладка',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: 'https://images.unsplash.com/photo-1584530313715-bfe628686135?w=600&h=600&fit=crop',
    gallery: [],
    description: 'Идеально белая поверхность. Минималистичное решение для чистых и светлых пространств.',
    specs: { 'Толщина накладки': '3 мм', 'Материал': 'Полимер с УФ-печатью', 'Класс': 'Стандарт', 'Уход': 'Влажная уборка', 'Монтаж': 'Магнитное крепление' },
    colors: [
      { hex: '#FFFFFF', name: 'Белый' },
      { hex: '#FAFAFA', name: 'Снежный' },
      { hex: '#F5F5F5', name: 'Молочный' },
    ],
    sizes: [...PANEL_SIZES],
    rating: 4.3,
    reviews: 167,
    inStock: true,
    room: ['Любое помещение'],
    usageExamples: [
      { room: 'Гостиная', image: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=1200&h=800&fit=crop', caption: 'Абсолютная чистота. Белый не просто цвет — это состояние.' },
      { room: 'Ванная', image: 'https://images.unsplash.com/photo-1507652955-f3dcef5a3be5?w=1200&h=800&fit=crop', caption: 'Свет и простота. Ванная как место тишины.' },
      { room: 'Кухня', image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&h=800&fit=crop', caption: 'Белый усиливает естественный свет. Кухня дышит.' },
    ],
  },
];

export const clientReviews: Review[] = [
  { id: '1', author: 'Анна К.', rating: 5, text: 'Установили панели с дубовой накладкой в гостиной. Монтаж на магниты — 2 часа, результат потрясающий! Все гости спрашивают, откуда такая красота.', date: '2026-02-15' },
  { id: '2', author: 'Михаил С.', rating: 5, text: 'Конструктор на сайте помог подобрать идеальную комбинацию. Взял подписку — теперь меняю дизайн накладок каждый сезон.', date: '2026-01-28' },
  { id: '3', author: 'Елена В.', rating: 4, text: 'Отличное качество мраморных накладок. Стена стала настоящим арт-объектом. Рекомендую!', date: '2026-03-02' },
  { id: '4', author: 'Дмитрий П.', rating: 5, text: 'Самое крутое — это то что все накладки стоят одинаково. Никаких сюрпризов с ценой. Бетон лофт выглядит роскошно.', date: '2026-02-20' },
];
