import type { PanelProduct, Category, Review } from './types';
import { PANEL_SIZES, DESIGN_OVERLAY_PRICE } from '../../../shared/config/constants';

export const categories: Category[] = [
  { key: 'all', label: 'Все дизайны', image: '', count: 0 },
  { key: 'wood', label: 'Дерево', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400&h=300&fit=crop', count: 3 },
  { key: 'stone', label: 'Камень', image: 'https://images.unsplash.com/photo-1615529182904-14819c35db37?w=400&h=300&fit=crop', count: 2 },
  { key: 'abstract', label: 'Абстракция', image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&h=300&fit=crop', count: 2 },
  { key: 'geometric', label: 'Геометрия', image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&h=300&fit=crop', count: 2 },
  { key: 'nature', label: 'Природа', image: 'https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=400&h=300&fit=crop', count: 2 },
  { key: 'minimal', label: 'Минимализм', image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400&h=300&fit=crop', count: 2 },
];

export const products: PanelProduct[] = [
  {
    id: 'design-oak-classic',
    name: 'Дубовая классика',
    category: 'wood',
    categoryLabel: 'Дерево',
    style: 'Классика',
    material: 'Накладка с текстурой дуба',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=600&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800&h=600&fit=crop',
    ],
    description: 'Накладка с текстурой натурального дуба. Реалистичная фактура, тёплый древесный оттенок. Подходит для гостиных, кабинетов и спален.',
    specs: { 'Толщина накладки': '3 мм', 'Материал': 'Полимер с УФ-печатью', 'Класс': 'Премиум', 'Уход': 'Влажная уборка', 'Монтаж': 'Магнитное крепление' },
    colors: [
      { hex: '#8B6914', name: 'Натуральный дуб' },
      { hex: '#A0522D', name: 'Тёмный дуб' },
      { hex: '#D2B48C', name: 'Светлый дуб' },
      { hex: '#6B4226', name: 'Шоколад' },
    ],
    sizes: [...PANEL_SIZES],
    rating: 4.8,
    reviews: 124,
    badge: 'Хит',
    inStock: true,
    room: ['Гостиная', 'Кабинет', 'Спальня'],
  },
  {
    id: 'design-walnut',
    name: 'Американский орех',
    category: 'wood',
    categoryLabel: 'Дерево',
    style: 'Классика',
    material: 'Накладка с текстурой ореха',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=600&h=600&fit=crop',
    gallery: [],
    description: 'Роскошная накладка с текстурой американского ореха. Глубокий шоколадный оттенок для элегантных интерьеров.',
    specs: { 'Толщина накладки': '3 мм', 'Материал': 'Полимер с УФ-печатью', 'Класс': 'Люкс', 'Уход': 'Влажная уборка', 'Монтаж': 'Магнитное крепление' },
    colors: [
      { hex: '#3E2723', name: 'Тёмный орех' },
      { hex: '#5D4037', name: 'Классический' },
      { hex: '#4E342E', name: 'Мокко' },
    ],
    sizes: [...PANEL_SIZES],
    rating: 4.9,
    reviews: 87,
    badge: 'Премиум',
    inStock: true,
    room: ['Гостиная', 'Кабинет'],
  },
  {
    id: 'design-ash',
    name: 'Ясень скандинавский',
    category: 'wood',
    categoryLabel: 'Дерево',
    style: 'Минимализм',
    material: 'Накладка с текстурой ясеня',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: 'https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=600&h=600&fit=crop',
    gallery: [],
    description: 'Светлая накладка в скандинавском стиле с текстурой ясеня. Минималистичный и воздушный дизайн.',
    specs: { 'Толщина накладки': '3 мм', 'Материал': 'Полимер с УФ-печатью', 'Класс': 'Премиум', 'Уход': 'Влажная уборка', 'Монтаж': 'Магнитное крепление' },
    colors: [
      { hex: '#F5DEB3', name: 'Натуральный' },
      { hex: '#FAEBD7', name: 'Отбелённый' },
      { hex: '#DEB887', name: 'Медовый' },
    ],
    sizes: [...PANEL_SIZES],
    rating: 4.7,
    reviews: 56,
    inStock: true,
    room: ['Спальня', 'Детская', 'Гостиная'],
  },
  {
    id: 'design-marble',
    name: 'Белый мрамор',
    category: 'stone',
    categoryLabel: 'Камень',
    style: 'Модерн',
    material: 'Накладка с текстурой мрамора',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: 'https://images.unsplash.com/photo-1615529182904-14819c35db37?w=600&h=600&fit=crop',
    gallery: [],
    description: 'Изысканная мраморная текстура с тонкими прожилками. Элегантное решение для любого интерьера.',
    specs: { 'Толщина накладки': '3 мм', 'Материал': 'Полимер с УФ-печатью', 'Класс': 'Люкс', 'Уход': 'Влажная уборка', 'Монтаж': 'Магнитное крепление' },
    colors: [
      { hex: '#F5F5F5', name: 'Каррара' },
      { hex: '#E8E0D8', name: 'Калакатта' },
      { hex: '#D3D3D3', name: 'Серый мрамор' },
    ],
    sizes: [...PANEL_SIZES],
    rating: 4.8,
    reviews: 156,
    badge: 'Новинка',
    inStock: true,
    room: ['Гостиная', 'Ванная', 'Кухня'],
  },
  {
    id: 'design-concrete',
    name: 'Бетон лофт',
    category: 'stone',
    categoryLabel: 'Камень',
    style: 'Лофт',
    material: 'Накладка с текстурой бетона',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: 'https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=600&h=600&fit=crop',
    gallery: [],
    description: 'Имитация бетонной поверхности для стиля лофт. Современный индустриальный вид.',
    specs: { 'Толщина накладки': '3 мм', 'Материал': 'Полимер с УФ-печатью', 'Класс': 'Стандарт', 'Уход': 'Влажная уборка', 'Монтаж': 'Магнитное крепление' },
    colors: [
      { hex: '#9E9E9E', name: 'Светлый бетон' },
      { hex: '#616161', name: 'Тёмный бетон' },
      { hex: '#BDBDBD', name: 'Серый' },
    ],
    sizes: [...PANEL_SIZES],
    rating: 4.5,
    reviews: 203,
    inStock: true,
    room: ['Гостиная', 'Кабинет', 'Кухня'],
  },
  {
    id: 'design-waves',
    name: 'Волны',
    category: 'abstract',
    categoryLabel: 'Абстракция',
    style: 'Модерн',
    material: 'Накладка с абстрактным паттерном',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&h=600&fit=crop',
    gallery: [],
    description: 'Динамичный абстрактный паттерн с волнообразным рисунком. Создаёт движение и глубину.',
    specs: { 'Толщина накладки': '3 мм', 'Материал': 'Полимер с УФ-печатью', 'Класс': 'Премиум', 'Уход': 'Влажная уборка', 'Монтаж': 'Магнитное крепление' },
    colors: [
      { hex: '#1A237E', name: 'Индиго' },
      { hex: '#006064', name: 'Океан' },
      { hex: '#4A148C', name: 'Аметист' },
    ],
    sizes: [...PANEL_SIZES],
    rating: 4.7,
    reviews: 98,
    inStock: true,
    room: ['Гостиная', 'Спальня'],
  },
  {
    id: 'design-gradient',
    name: 'Градиент',
    category: 'abstract',
    categoryLabel: 'Абстракция',
    style: 'Арт',
    material: 'Накладка с градиентом',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=600&h=600&fit=crop',
    gallery: [],
    description: 'Плавные цветовые переходы. Арт-объект на вашей стене. Каждая панель уникальна.',
    specs: { 'Толщина накладки': '3 мм', 'Материал': 'Полимер с УФ-печатью', 'Класс': 'Премиум', 'Уход': 'Влажная уборка', 'Монтаж': 'Магнитное крепление' },
    colors: [
      { hex: '#FF6B6B', name: 'Закат' },
      { hex: '#4ECDC4', name: 'Мята' },
      { hex: '#2C3E50', name: 'Ночь' },
    ],
    sizes: [...PANEL_SIZES],
    rating: 4.6,
    reviews: 78,
    inStock: true,
    room: ['Гостиная', 'Кафе', 'Офис'],
  },
  {
    id: 'design-hexagon',
    name: 'Гексагон',
    category: 'geometric',
    categoryLabel: 'Геометрия',
    style: 'Модерн',
    material: 'Накладка с геометрическим паттерном',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=600&fit=crop',
    gallery: [],
    description: 'Шестиугольный геометрический паттерн. Современный и стильный дизайн для любого пространства.',
    specs: { 'Толщина накладки': '3 мм', 'Материал': 'Полимер с УФ-печатью', 'Класс': 'Премиум', 'Уход': 'Влажная уборка', 'Монтаж': 'Магнитное крепление' },
    colors: [
      { hex: '#2D2D2D', name: 'Графит' },
      { hex: '#FFFFFF', name: 'Белый' },
      { hex: '#B87333', name: 'Медь' },
      { hex: '#1ABC9C', name: 'Бирюза' },
    ],
    sizes: [...PANEL_SIZES],
    rating: 4.5,
    reviews: 143,
    inStock: true,
    room: ['Ванная', 'Кухня', 'Прихожая'],
  },
  {
    id: 'design-lines',
    name: 'Линии',
    category: 'geometric',
    categoryLabel: 'Геометрия',
    style: 'Минимализм',
    material: 'Накладка с линейным паттерном',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: 'https://images.unsplash.com/photo-1600566753086-00f18f6b0049?w=600&h=600&fit=crop',
    gallery: [],
    description: 'Строгие вертикальные линии. Ритмичный минималистичный рисунок для элегантных интерьеров.',
    specs: { 'Толщина накладки': '3 мм', 'Материал': 'Полимер с УФ-печатью', 'Класс': 'Стандарт', 'Уход': 'Влажная уборка', 'Монтаж': 'Магнитное крепление' },
    colors: [
      { hex: '#FFFFFF', name: 'Белый' },
      { hex: '#1A1A1A', name: 'Чёрный' },
      { hex: '#9CA3AF', name: 'Серебро' },
    ],
    sizes: [...PANEL_SIZES],
    rating: 4.4,
    reviews: 89,
    inStock: true,
    room: ['Кабинет', 'Прихожая', 'Офис'],
  },
  {
    id: 'design-tropical',
    name: 'Тропики',
    category: 'nature',
    categoryLabel: 'Природа',
    style: 'Модерн',
    material: 'Накладка с тропическим принтом',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: 'https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=600&h=600&fit=crop',
    gallery: [],
    description: 'Тропические листья и растения. Оживите интерьер природными мотивами.',
    specs: { 'Толщина накладки': '3 мм', 'Материал': 'Полимер с УФ-печатью', 'Класс': 'Премиум', 'Уход': 'Влажная уборка', 'Монтаж': 'Магнитное крепление' },
    colors: [
      { hex: '#2E7D32', name: 'Зелёный' },
      { hex: '#1B5E20', name: 'Тёмно-зелёный' },
      { hex: '#4CAF50', name: 'Свежая зелень' },
    ],
    sizes: [...PANEL_SIZES],
    rating: 4.6,
    reviews: 67,
    badge: 'Новинка',
    inStock: true,
    room: ['Спальня', 'Гостиная', 'Детская'],
  },
  {
    id: 'design-botanical',
    name: 'Ботаника',
    category: 'nature',
    categoryLabel: 'Природа',
    style: 'Арт',
    material: 'Накладка с ботаническим принтом',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=600&h=600&fit=crop',
    gallery: [],
    description: 'Нежные ботанические иллюстрации. Утончённый дизайн для уютных пространств.',
    specs: { 'Толщина накладки': '3 мм', 'Материал': 'Полимер с УФ-печатью', 'Класс': 'Премиум', 'Уход': 'Влажная уборка', 'Монтаж': 'Магнитное крепление' },
    colors: [
      { hex: '#F5F5DC', name: 'Крем' },
      { hex: '#FFF8E1', name: 'Ваниль' },
      { hex: '#E8F5E9', name: 'Мятный' },
    ],
    sizes: [...PANEL_SIZES],
    rating: 4.8,
    reviews: 42,
    inStock: true,
    room: ['Спальня', 'Гостиная', 'Кафе'],
  },
  {
    id: 'design-pure-white',
    name: 'Чистый белый',
    category: 'minimal',
    categoryLabel: 'Минимализм',
    style: 'Минимализм',
    material: 'Белая однотонная накладка',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=600&h=600&fit=crop',
    gallery: [],
    description: 'Идеально белая поверхность. Минималистичное решение для чистых и светлых пространств.',
    specs: { 'Толщина накладки': '3 мм', 'Материал': 'Полимер с УФ-печатью', 'Класс': 'Стандарт', 'Уход': 'Влажная уборка', 'Монтаж': 'Магнитное крепление' },
    colors: [
      { hex: '#FFFFFF', name: 'Белый' },
      { hex: '#FAFAFA', name: 'Снежный' },
      { hex: '#F5F5F5', name: 'Молочный' },
    ],
    sizes: [...PANEL_SIZES],
    rating: 4.3,
    reviews: 167,
    inStock: true,
    room: ['Любое помещение'],
  },
];

export const clientReviews: Review[] = [
  { id: '1', author: 'Анна К.', rating: 5, text: 'Установили панели с дубовой накладкой в гостиной. Монтаж на магниты — 2 часа, результат потрясающий! Все гости спрашивают, откуда такая красота.', date: '2026-02-15' },
  { id: '2', author: 'Михаил С.', rating: 5, text: 'Конструктор на сайте помог подобрать идеальную комбинацию. Взял подписку — теперь меняю дизайн накладок каждый сезон.', date: '2026-01-28' },
  { id: '3', author: 'Елена В.', rating: 4, text: 'Отличное качество мраморных накладок. Стена стала настоящим арт-объектом. Рекомендую!', date: '2026-03-02' },
  { id: '4', author: 'Дмитрий П.', rating: 5, text: 'Самое крутое — это то что все накладки стоят одинаково. Никаких сюрпризов с ценой. Бетон лофт выглядит роскошно.', date: '2026-02-20' },
];
