import type { PanelProduct, Category, Review } from './types';
import { PANEL_SIZES, DESIGN_OVERLAY_PRICE } from '../../../shared/config/constants';

export const categories: Category[] = [
  { key: 'all', label: 'Все формы', image: '', count: 0 },
  { key: 'cat-30x30', label: '30×30 см', image: '/uploads/forms/30x30/flat-s-01-front.png', count: 14 },
  { key: 'cat-30x60', label: '30×60 см', image: '/uploads/forms/30x60/flat-m-01-front.png', count: 12 },
  { key: 'cat-60x60', label: '60×60 см', image: '/uploads/forms/60x60/flat-l-01-front.png', count: 11 },
];

export const products: PanelProduct[] = [
  {
    id: 'herringbone-01',
    name: 'Ёлочка',
    category: 'cat-30x30',
    categoryLabel: '',
    style: '',
    material: '',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: '/uploads/forms/30x30/herringbone-01-front.png',
    previewImage: '/uploads/forms/30x30/herringbone-01-front.png',
    gallery: [],
    description: 'Классическая ёлочка — строгий геометрический узор, который подходит для любого интерьера.',
    specs: {},
    colors: [],
    sizes: [...PANEL_SIZES],
    rating: 4.9,
    reviews: 87,
    badge: 'Новинка',
    inStock: true,
    room: ['Гостиная', 'Спальня', 'Кабинет'],
    usageExamples: [],
  },
  {
    id: 'herringbone-frame-01',
    name: 'Рамочная',
    category: 'cat-30x30',
    categoryLabel: '',
    style: '',
    material: '',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: '/uploads/forms/30x30/herringbone-frame-01-front.png',
    previewImage: '/uploads/forms/30x30/herringbone-frame-01-front.png',
    gallery: [],
    description: 'Рамочная панель — аккуратный геометрический рисунок для стильного интерьера.',
    specs: {},
    colors: [],
    sizes: [...PANEL_SIZES],
    rating: 4.8,
    reviews: 64,
    badge: 'Популярное',
    inStock: true,
    room: ['Гостиная', 'Холл', 'Офис'],
    usageExamples: [],
  },
  {
    id: 'crel-l-03',
    name: 'Классический рельеф',
    category: 'cat-60x60',
    categoryLabel: '',
    style: '',
    material: '',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: '/uploads/forms/60x60/crel-l-03-front.png',
    previewImage: '/uploads/forms/60x60/crel-l-03-front.png',
    gallery: [],
    description: 'Традиционный филёнчатый рельеф большого формата.',
    specs: {},
    colors: [],
    sizes: [...PANEL_SIZES],
    rating: 4.9,
    reviews: 72,
    badge: 'Популярное',
    inStock: true,
    room: ['Гостиная', 'Спальня', 'Ресторан'],
    usageExamples: [
      { room: 'Гостиная', image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=500&fit=crop', caption: 'Классика в просторной гостиной' },
      { room: 'Ресторан', image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=500&fit=crop', caption: 'Рельефная стена в ресторане' },
      { room: 'Спальня', image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&h=500&fit=crop', caption: 'Уютная спальня с панелями' },
    ],
  },
  {
    id: 'arc-s-07',
    name: 'Арка',
    category: 'cat-30x30',
    categoryLabel: '',
    style: '',
    material: '',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: '/uploads/forms/30x30/arc-s-07-front.png',
    previewImage: '/uploads/forms/30x30/arc-s-07-front.png',
    gallery: [],
    description: 'Изящная арка — плавные линии для современного интерьера.',
    specs: {},
    colors: [],
    sizes: [...PANEL_SIZES],
    rating: 4.7,
    reviews: 45,
    badge: '',
    inStock: true,
    room: ['Гостиная', 'Спальня'],
    usageExamples: [],
  },
  {
    id: 'cir-l-06',
    name: 'Круг',
    category: 'cat-60x60',
    categoryLabel: '',
    style: '',
    material: '',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: '/uploads/forms/60x60/cir-l-06-front.png',
    previewImage: '/uploads/forms/60x60/cir-l-06-front.png',
    gallery: [],
    description: 'Минималистичный круг — акцентная деталь любого пространства.',
    specs: {},
    colors: [],
    sizes: [...PANEL_SIZES],
    rating: 4.8,
    reviews: 58,
    badge: 'Новинка',
    inStock: true,
    room: ['Гостиная', 'Офис', 'Холл'],
    usageExamples: [],
  },
  {
    id: 'wav-s-10',
    name: 'Волна',
    category: 'cat-30x30',
    categoryLabel: '',
    style: '',
    material: '',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: '/uploads/forms/30x30/wav-s-10-front.png',
    previewImage: '/uploads/forms/30x30/wav-s-10-front.png',
    gallery: [],
    description: 'Элегантная волна — динамика и движение в вашем интерьере.',
    specs: {},
    colors: [],
    sizes: [...PANEL_SIZES],
    rating: 4.6,
    reviews: 39,
    badge: '',
    inStock: true,
    room: ['Гостиная', 'Ванная', 'Балкон'],
    usageExamples: [],
  },
  {
    id: 'cfrm-l-11',
    name: 'Кассета',
    category: 'cat-60x60',
    categoryLabel: '',
    style: '',
    material: '',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: '/uploads/forms/60x60/cfrm-l-11-front.png',
    previewImage: '/uploads/forms/60x60/cfrm-l-11-front.png',
    gallery: [],
    description: 'Геометрическая кассета — строгий стиль для офиса и лобби.',
    specs: {},
    colors: [],
    sizes: [...PANEL_SIZES],
    rating: 4.9,
    reviews: 81,
    badge: 'Популярное',
    inStock: true,
    room: ['Офис', 'Холл', 'Ресторан'],
    usageExamples: [],
  },
  {
    id: 'zig-s-09',
    name: 'Зигзаг',
    category: 'cat-30x30',
    categoryLabel: '',
    style: '',
    material: '',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: '/uploads/forms/30x30/zig-s-09-front.png',
    previewImage: '/uploads/forms/30x30/zig-s-09-front.png',
    gallery: [],
    description: 'Яркий зигзаг — энергия и характер для смелых решений.',
    specs: {},
    colors: [],
    sizes: [...PANEL_SIZES],
    rating: 4.5,
    reviews: 28,
    badge: '',
    inStock: true,
    room: ['Детская', 'Гостиная', 'Студия'],
    usageExamples: [],
  },
  {
    id: 'mos-l-08',
    name: 'Мозаика',
    category: 'cat-60x60',
    categoryLabel: '',
    style: '',
    material: '',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: '/uploads/forms/60x60/mos-l-08-front.png',
    previewImage: '/uploads/forms/60x60/mos-l-08-front.png',
    gallery: [],
    description: 'Роскошная мозаика — сложный узор для впечатляющего эффекта.',
    specs: {},
    colors: [],
    sizes: [...PANEL_SIZES],
    rating: 4.8,
    reviews: 52,
    badge: '',
    inStock: true,
    room: ['Гостиная', 'Спальня', 'Ресторан'],
    usageExamples: [],
  },
  {
    id: 'pyr-s-12',
    name: 'Пирамида',
    category: 'cat-30x30',
    categoryLabel: '',
    style: '',
    material: '',
    price: DESIGN_OVERLAY_PRICE,
    priceUnit: '/шт',
    image: '/uploads/forms/30x30/pyr-s-12-front.png',
    previewImage: '/uploads/forms/30x30/pyr-s-12-front.png',
    gallery: [],
    description: 'Стильная пирамида — игра света и тени на вашей стене.',
    specs: {},
    colors: [],
    sizes: [...PANEL_SIZES],
    rating: 4.7,
    reviews: 41,
    badge: '',
    inStock: true,
    room: ['Гостиная', 'Кабинет', 'Библиотека'],
    usageExamples: [],
  },
];

export const reviews: Review[] = [];

export const clientReviews = [
  {
    id: 'cr-1',
    author: 'Анна Смирнова',
    rating: 5,
    text: 'Панели превзошли все ожидания! Установка прошла легко, результат потрясающий. Гостиная преобразилась полностью.',
    date: '2025-03-15',
  },
  {
    id: 'cr-2',
    author: 'Михаил Козлов',
    rating: 5,
    text: 'Заказывал «Волну» для спальни. Качество материала отличное, рельеф именно такой, как на фото. Очень доволен покупкой.',
    date: '2025-02-28',
  },
  {
    id: 'cr-3',
    author: 'Елена Новикова',
    rating: 4,
    text: 'Красивые панели, хороший сервис. Доставка чуть задержалась, но результат стоит того — стена смотрится роскошно.',
    date: '2025-04-03',
  },
  {
    id: 'cr-4',
    author: 'Дмитрий Петров',
    rating: 5,
    text: 'Использовали «Кессон» для акцентной стены в офисе. Клиенты в восторге! Обязательно закажем ещё.',
    date: '2025-01-20',
  },
  {
    id: 'cr-5',
    author: 'Ольга Иванова',
    rating: 5,
    text: 'Панели «Классический рельеф» — это нечто! Создают ощущение дорогого интерьера. Рекомендую всем.',
    date: '2025-03-30',
  },
  {
    id: 'cr-6',
    author: 'Алексей Фёдоров',
    rating: 4,
    text: 'Отличное соотношение цены и качества. Монтаж несложный, инструкция понятная. Стена выглядит стильно.',
    date: '2025-04-12',
  },
];
