"""Add typed perspective + calibration columns + optimistic-lock version.

Phase 5B: extends `visualization_projects` with the columns the new domain
VOs (`PerspectiveCorners`, `ScaleCalibration`) need, plus the `version`
counter for multi-tab race protection (E8 in plan).

Existing columns kept untouched:
    - `calibration_pixels_per_cm` (legacy float; stays during 5B/5C
      transition; 5C may deprecate after the API switches to the typed VO)
    - `perspective_corners` (legacy raw JSON of 4 points; same lifecycle)

New columns:
    - `calibration JSON` — `{method, pixels_per_cm, wall_width_cm?, wall_height_cm?}`
    - `perspective_auto_detected BOOLEAN NOT NULL DEFAULT FALSE`
    - `calibration_auto_detected BOOLEAN NOT NULL DEFAULT FALSE`
    - `version INTEGER NOT NULL DEFAULT 1`

JSON (not JSONB) to match the existing `panels_json`/`perspective_corners`
columns and stay portable to the SQLite test rig (sa.JSON maps to TEXT on
sqlite, JSON on postgres). A future migration may switch to JSONB on pg
for indexed lookups, but Phase 5B has no read pattern that needs it.

Revision ID: 005
Revises: 004
Create Date: 2026-04-24
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "005"
down_revision: Union[str, None] = "004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # `server_default` on the bool/int columns so existing rows backfill
    # without a separate UPDATE pass — important for postgres prod where
    # the table may already hold scenes from 5A.
    op.add_column(
        "visualization_projects",
        sa.Column("calibration", sa.JSON, nullable=True),
    )
    op.add_column(
        "visualization_projects",
        sa.Column(
            "perspective_auto_detected",
            sa.Boolean,
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column(
        "visualization_projects",
        sa.Column(
            "calibration_auto_detected",
            sa.Boolean,
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column(
        "visualization_projects",
        sa.Column(
            "version",
            sa.Integer,
            nullable=False,
            server_default="1",
        ),
    )


def downgrade() -> None:
    # Reverse order — `op.drop_column` works on SQLite ≥ 3.35 natively
    # (env.py keeps `render_as_batch=True` for future autogenerated migrations).
    op.drop_column("visualization_projects", "version")
    op.drop_column("visualization_projects", "calibration_auto_detected")
    op.drop_column("visualization_projects", "perspective_auto_detected")
    op.drop_column("visualization_projects", "calibration")
